apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
    - image: users-service
      context: users
      docker:
        dockerfile: docker/backend.dockerfile
    - image: users-worker-service
      context: users
      docker:
        dockerfile: docker/worker.dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/*
portForward:
  - resourceType: deployment
    resourceName: users-deployment
    port: 80
    localPort: 8000
test:
  - image: users-deployment
    custom:
      - command: pytest
