apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: users-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: users-service
          ports:
            - containerPort: 80
